package com.utagent.ci;

import java.util.List;
import java.util.Map;

public class PRCommentGenerator {

    private String template;

    public String generateCoverageComment(CoverageSummary summary) {
        StringBuilder sb = new StringBuilder();
        
        sb.append("## 📊 Coverage Report\n\n");
        
        String lineBadge = getCoverageBadge(summary.lineCoverage());
        String branchBadge = getCoverageBadge(summary.branchCoverage());
        
        sb.append("| Type | Coverage | Status |\n");
        sb.append("|------|----------|--------|\n");
        sb.append(String.format("| Line | %s | %s |\n", summary.getLineCoveragePercent(), lineBadge));
        sb.append(String.format("| Branch | %s | %s |\n", summary.getBranchCoveragePercent(), branchBadge));
        sb.append(String.format("| Instruction | %.0f%% | %s |\n", 
            summary.instructionCoverage() * 100, getCoverageBadge(summary.instructionCoverage())));
        sb.append(String.format("| Method | %.0f%% | %s |\n", 
            summary.methodCoverage() * 100, getCoverageBadge(summary.methodCoverage())));
        
        sb.append(String.format("\n**Overall Coverage:** %.0f%%\n", summary.getOverallCoverage() * 100));
        
        return sb.toString();
    }

    public String generateCoverageChangeComment(CoverageSummary current, CoverageSummary previous) {
        StringBuilder sb = new StringBuilder();
        
        sb.append("## 📈 Coverage Change\n\n");
        
        double lineChange = (current.lineCoverage() - previous.lineCoverage()) * 100;
        double branchChange = (current.branchCoverage() - previous.branchCoverage()) * 100;
        double overallChange = (current.getOverallCoverage() - previous.getOverallCoverage()) * 100;
        
        sb.append("| Type | Before | After | Change |\n");
        sb.append("|------|--------|-------|--------|\n");
        sb.append(String.format("| Line | %.0f%% | %.0f%% | %s |\n", 
            previous.lineCoverage() * 100, current.lineCoverage() * 100, formatChange(lineChange)));
        sb.append(String.format("| Branch | %.0f%% | %.0f%% | %s |\n", 
            previous.branchCoverage() * 100, current.branchCoverage() * 100, formatChange(branchChange)));
        sb.append(String.format("| **Overall** | %.0f%% | %.0f%% | %s |\n", 
            previous.getOverallCoverage() * 100, current.getOverallCoverage() * 100, formatChange(overallChange)));
        
        if (overallChange > 0) {
            sb.append("\n✅ Coverage **improved** by ").append(String.format("%.1f%%", overallChange)).append("\n");
        } else if (overallChange < 0) {
            sb.append("\n⚠️ Coverage **decreased** by ").append(String.format("%.1f%%", Math.abs(overallChange))).append("\n");
        } else {
            sb.append("\n➡️ Coverage **unchanged**\n");
        }
        
        return sb.toString();
    }

    public String generateQualityComment(QualityScore score) {
        StringBuilder sb = new StringBuilder();
        
        sb.append("## 🏆 Quality Score\n\n");
        
        String gradeEmoji = getGradeEmoji(score.getGrade());
        sb.append(String.format("**Score:** %.0f/100 %s\n\n", score.overallScore(), gradeEmoji));
        
        sb.append("| Dimension | Score | Weight |\n");
        sb.append("|-----------|-------|--------|\n");
        
        for (Map.Entry<String, Double> entry : score.dimensionScores().entrySet()) {
            sb.append(String.format("| %s | %.0f | - |\n", 
                capitalize(entry.getKey()), entry.getValue()));
        }
        
        if (score.overallScore() < 70) {
            sb.append("\n### 💡 Improvement Suggestions\n");
            if (score.dimensionScores().getOrDefault("coverage", 0.0) < 20) {
                sb.append("- Increase test coverage for better reliability\n");
            }
            if (score.dimensionScores().getOrDefault("mutation", 0.0) < 25) {
                sb.append("- Add more meaningful assertions to catch mutations\n");
            }
            if (score.dimensionScores().getOrDefault("readability", 0.0) < 12) {
                sb.append("- Improve test naming and add descriptive messages\n");
            }
        }
        
        return sb.toString();
    }

    public String generateNewTestsComment(List<String> newTests) {
        StringBuilder sb = new StringBuilder();
        
        sb.append("## 🧪 New Tests Generated\n\n");
        sb.append(String.format("**%d new test files** were generated:\n\n", newTests.size()));
        
        for (String test : newTests) {
            sb.append("- `").append(test).append("`\n");
        }
        
        sb.append("\n> Generated by [Java UT Agent](https://github.com/java-ut-agent)\n");
        
        return sb.toString();
    }

    public String generateStatusComment(PRStatus status) {
        StringBuilder sb = new StringBuilder();
        
        sb.append("## ").append(status.getStatusEmoji()).append(" Test Status\n\n");
        
        sb.append(String.format("**Status:** %s\n\n", status.getStatusText()));
        sb.append(String.format("**Message:** %s\n\n", status.message()));
        sb.append(String.format("**Coverage:** %.0f%%\n", status.coverage() * 100));
        sb.append(String.format("**Quality Score:** %.0f/100\n", status.qualityScore()));
        
        return sb.toString();
    }

    public void setTemplate(String template) {
        this.template = template;
    }

    public String generateFromTemplate(CoverageSummary summary) {
        if (template == null || template.isEmpty()) {
            return generateCoverageComment(summary);
        }
        
        String result = template;
        result = result.replace("{{coverage}}", String.format("%.0f", summary.getOverallCoverage() * 100));
        result = result.replace("{{lineCoverage}}", summary.getLineCoveragePercent());
        result = result.replace("{{branchCoverage}}", summary.getBranchCoveragePercent());
        
        return result;
    }

    private String getCoverageBadge(double coverage) {
        if (coverage >= 0.8) return "🟢";
        if (coverage >= 0.6) return "🟡";
        return "🔴";
    }

    private String formatChange(double change) {
        if (change > 0) {
            return String.format("+%.1f%%", change);
        } else if (change < 0) {
            return String.format("%.1f%%", change);
        }
        return "0.0%";
    }

    private String getGradeEmoji(String grade) {
        return switch (grade) {
            case "A" -> "🌟";
            case "B" -> "👍";
            case "C" -> "👌";
            case "D" -> "⚠️";
            default -> "❌";
        };
    }

    private String capitalize(String str) {
        if (str == null || str.isEmpty()) return str;
        return Character.toUpperCase(str.charAt(0)) + str.substring(1);
    }
}
